import type { Job, Resume } from '@/types';

/**
 * Mock 数据 —— 迁移自 prototype/data.js，类型化后供 M1.2 静态页消费。
 * M1.3 起 Prisma seed 会读这份数据写入 DB；本文件保留作 fixture。
 */

export const SEED_JOBS: Job[] = [
  {
    id: 'JD-2024-0118',
    title: '高级前端工程师',
    dept: '技术中心 · Web 平台组',
    level: 'P7',
    location: '杭州 / 上海',
    salary: '30-55K · 16薪',
    type: '全职',
    status: '招聘中',
    owner: '李工 (用人经理)',
    hr: '陈思雨',
    headcount: 2,
    resumes: 28,
    interviewed: 6,
    offer: 1,
    createdAt: '2024-05-11',
    skills: ['React', 'TypeScript', '性能优化', '微前端', 'Node.js'],
    description:
      '负责公司核心 SaaS 产品的前端架构演进与新功能研发。深度参与从 0 到 1 的技术决策，主导前端基建（脚手架、组件库、监控）建设，与产品/设计/后端密切协作交付高质量体验。',
    responsibilities: [
      '主导核心业务模块的前端架构设计与代码实现',
      '推进微前端、性能监控、自动化测试等基础设施落地',
      'Code Review、技术分享，帮助团队成员成长',
      '与产品、设计深度协作，对最终用户体验负责',
    ],
    requirements: [
      '本科及以上学历，计算机相关专业，5 年以上前端研发经验',
      '精通 React 生态、TypeScript，熟悉 Webpack/Vite 构建原理',
      '有完整的大型 Web 应用架构与性能优化经验',
      '有微前端、SSR、低代码或可视化搭建经验者优先',
      '良好的工程素养与跨团队沟通能力',
    ],
    nice: ['有开源项目或技术博客', '有 Node.js / BFF 经验'],
  },
  {
    id: 'JD-2024-0121',
    title: 'AI 产品经理',
    dept: '产品中心 · AI 创新组',
    level: 'P6 / P7',
    location: '北京',
    salary: '35-60K · 15薪',
    type: '全职',
    status: '招聘中',
    owner: '周明 (产品总监)',
    hr: '陈思雨',
    headcount: 1,
    resumes: 19,
    interviewed: 4,
    offer: 0,
    createdAt: '2024-05-09',
    skills: ['LLM 应用', 'Agent', '用户增长', '数据分析', '原型设计'],
    description: '负责 AI 助手产品线规划与落地，从用户洞察到产品设计、再到上线运营全流程把控。',
    responsibilities: [
      '深入理解大模型/Agent 能力边界，识别有价值的场景',
      '完成产品方案、PRD、原型设计，推动跨团队落地',
      '通过数据分析持续迭代，优化关键漏斗指标',
    ],
    requirements: [
      '3 年以上互联网产品经验，有 AI/工具类产品背景者优先',
      '对 LLM、Prompt、Agent、RAG 等概念有实战理解',
      '强结构化思维与数据驱动意识',
      '良好的项目管理能力',
    ],
    nice: ['B 端 SaaS 经验', '前端/工程背景'],
  },
  {
    id: 'JD-2024-0114',
    title: '算法工程师 · 推荐',
    dept: '算法中台 · 推荐组',
    level: 'P6',
    location: '杭州',
    salary: '35-65K · 16薪',
    type: '全职',
    status: '招聘中',
    owner: 'Tang (算法负责人)',
    hr: '黄敏',
    headcount: 2,
    resumes: 34,
    interviewed: 8,
    offer: 2,
    createdAt: '2024-05-04',
    skills: ['推荐系统', 'Python', 'PyTorch', '特征工程', 'AB 实验'],
  },
  {
    id: 'JD-2024-0107',
    title: '高级 UI 设计师',
    dept: '设计中心 · 体验组',
    level: 'P5 / P6',
    location: '上海',
    salary: '22-38K · 14薪',
    type: '全职',
    status: '招聘中',
    owner: 'Linda',
    hr: '陈思雨',
    headcount: 1,
    resumes: 12,
    interviewed: 3,
    offer: 0,
    createdAt: '2024-04-29',
    skills: ['Figma', '设计系统', '动效', 'B 端体验', '插画'],
  },
  {
    id: 'JD-2024-0099',
    title: '数据分析师',
    dept: '数据中心 · 业务分析',
    level: 'P5',
    location: '深圳',
    salary: '20-35K · 14薪',
    type: '全职',
    status: '已暂停',
    owner: 'Will',
    hr: '黄敏',
    headcount: 1,
    resumes: 21,
    interviewed: 2,
    offer: 0,
    createdAt: '2024-04-18',
    skills: ['SQL', 'Python', 'Tableau', '用户行为分析'],
  },
  {
    id: 'JD-2024-0093',
    title: 'iOS 高级开发工程师',
    dept: '客户端 · iOS 组',
    level: 'P7',
    location: '北京',
    salary: '30-55K · 15薪',
    type: '全职',
    status: '草稿',
    owner: '宋阳',
    hr: '陈思雨',
    headcount: 1,
    resumes: 0,
    interviewed: 0,
    offer: 0,
    createdAt: '2024-04-10',
    skills: ['Swift', 'SwiftUI', '性能优化', '组件化'],
  },
];

export const SEED_RESUMES: Resume[] = [
  {
    id: 'R-9821',
    name: '张文轩',
    gender: '男',
    age: 30,
    edu: '硕士 · 浙江大学',
    yoe: 6,
    current: '字节跳动 · 高级前端工程师',
    expected: '40-55K',
    location: '杭州',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '今天 10:24',
    score: 92,
    breakdown: { skill: 95, experience: 92, education: 90, project: 96, stability: 82 },
    summary:
      '字节核心商业化前端 4 年，主导过两个亿级 DAU 业务的前端架构，开源 React 状态库 4k+ star。技术深度与项目复杂度均显著高于岗位预期。',
    pros: ['主导过亿级 DAU 业务的微前端落地', '开源作品社区影响力强', 'React/TypeScript 与岗位高度匹配'],
    cons: ['近一年跳槽频率略高（在字节内已转岗 2 次）'],
    interview: [
      '请详述你在字节主导的微前端方案中，跨团队版本管理如何治理？',
      '你的开源状态库与 Zustand 相比，核心差异是？',
      '如果让你重新设计公司当前的前端基建，你会如何取舍？',
    ],
    skills: ['React', 'TypeScript', 'Node.js', '微前端', '性能优化', 'Rust(初学)'],
    workHistory: [
      { co: '字节跳动', title: '高级前端工程师', dur: '2022.06 — 至今' },
      { co: '阿里巴巴 · 钉钉', title: '前端工程师', dur: '2019.07 — 2022.05' },
    ],
  },
  {
    id: 'R-9822',
    name: '李思琪',
    gender: '女',
    age: 28,
    edu: '本科 · 上海交通大学',
    yoe: 5,
    current: '美团 · 前端工程师',
    expected: '35-45K',
    location: '上海',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '今天 10:24',
    score: 88,
    breakdown: { skill: 90, experience: 85, education: 92, project: 88, stability: 90 },
    summary: '美团到家前端核心成员，5 年深耕 React 生态，完整经历多个 B 端产品 0→1，工程化基建沉淀扎实。',
    pros: ['在美团稳定 5 年，主导过完整设计系统建设', '技能栈与岗位 95% 重合', '有 Node.js BFF 经验'],
    cons: ['缺少明确的微前端实战项目'],
    interview: ['如果让你为我们的 SaaS 产品引入设计系统，你的落地路径是？', '在美团的 BFF 实践中，哪个决策事后看是错的？'],
    skills: ['React', 'TypeScript', 'Node.js', '设计系统', 'Webpack'],
  },
  {
    id: 'R-9823',
    name: '王俊豪',
    gender: '男',
    age: 32,
    edu: '本科 · 北京邮电大学',
    yoe: 7,
    current: '蚂蚁集团 · 技术专家',
    expected: '45-60K',
    location: '杭州',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '昨天 17:08',
    score: 85,
    breakdown: { skill: 88, experience: 95, education: 80, project: 90, stability: 75 },
    summary: '蚂蚁前端技术专家，7 年经验，主攻底层基建。在 SSR、CI/CD、可视化搭建方向有完整产出。',
    pros: ['资深技术专家身份', '底层基建经验完整', '薪资预期偏高但符合 P7 设定'],
    cons: ['近 2 段经历各 1.5 年，稳定性需追问', 'B 端业务深度较浅'],
    interview: ['蚂蚁的低代码搭建在你看来面临哪些根本性问题？', '为什么过去两段经历都没有超过 2 年？'],
    skills: ['React', 'Node.js', 'SSR', '低代码', '性能优化', 'Docker'],
  },
  {
    id: 'R-9824',
    name: '陈嘉怡',
    gender: '女',
    age: 27,
    edu: '本科 · 华中科技大学',
    yoe: 4,
    current: '拼多多 · 前端工程师',
    expected: '30-40K',
    location: '上海',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '昨天 16:42',
    score: 79,
    breakdown: { skill: 82, experience: 70, education: 85, project: 80, stability: 88 },
    summary: '拼多多用户增长前端组，业务节奏快、迭代密集，有大量 AB 实验前端落地经验。',
    pros: ['AB 实验/埋点经验对增长业务有帮助', '稳定性良好'],
    cons: ['年限略低于 5 年的硬性要求', '缺少架构级项目主导经验'],
    interview: ['增长前端如何与产品/算法协同的？', '你做过最有成就感的一次性能优化是？'],
    skills: ['React', 'TypeScript', 'AB 实验', '性能优化', 'Webpack'],
  },
  {
    id: 'R-9825',
    name: '刘子涵',
    gender: '男',
    age: 29,
    edu: '本科 · 武汉大学',
    yoe: 5,
    current: '滴滴 · 前端工程师',
    expected: '32-42K',
    location: '北京',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '前天',
    score: 76,
    breakdown: { skill: 78, experience: 80, education: 75, project: 72, stability: 80 },
    summary: '滴滴司机端前端，5 年经验，以业务交付为主。',
    pros: ['年限与经验范围匹配', 'C 端业务节奏熟悉'],
    cons: ['架构主导经验偏少', '技术广度可，深度待验证'],
    interview: ['如果由你主导一次新模块，你的拆解思路是？'],
    skills: ['React', 'TypeScript', 'Vue', 'Webpack'],
  },
  {
    id: 'R-9826',
    name: '周晓明',
    gender: '男',
    age: 31,
    edu: '本科 · 哈尔滨工业大学',
    yoe: 6,
    current: '京东 · 前端工程师',
    expected: '30-40K',
    location: '北京',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '前天',
    score: 72,
    breakdown: { skill: 70, experience: 82, education: 75, project: 68, stability: 70 },
    summary: '京东前端工程师，长期负责中后台维护，缺少新项目从 0→1 的经历。',
    pros: ['稳定的中后台维护经验'],
    cons: ['技能栈偏老（Vue2 + Webpack4 为主）', '项目主导力不足'],
    interview: ['你在过去 1 年中主动学习的新技术是？'],
    skills: ['Vue', 'React (基础)', 'Webpack', 'Element UI'],
  },
  {
    id: 'R-9827',
    name: '黄思敏',
    gender: '女',
    age: 26,
    edu: '硕士 · 同济大学',
    yoe: 3,
    current: '网易 · 前端工程师',
    expected: '25-35K',
    location: '杭州',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '3 天前',
    score: 68,
    breakdown: { skill: 75, experience: 55, education: 88, project: 70, stability: 85 },
    summary: '网易云音乐前端，3 年经验，成长快但年限低于岗位要求。',
    pros: ['教育背景优秀（同济硕士）', '学习能力强，技能栈较新'],
    cons: ['年限 3 年，距岗位 5 年硬性要求差距明显'],
    interview: ['你认为自己 5 年内能成长到 P7 吗？路径是什么？'],
    skills: ['React', 'TypeScript', 'Next.js'],
  },
  {
    id: 'R-9828',
    name: '林浩然',
    gender: '男',
    age: 28,
    edu: '本科 · 中山大学',
    yoe: 4,
    current: '小红书 · 前端工程师',
    expected: '30-38K',
    location: '上海',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '3 天前',
    score: 63,
    breakdown: { skill: 70, experience: 65, education: 70, project: 58, stability: 55 },
    summary: '小红书前端，4 年 3 段经历，稳定性较差。',
    pros: ['创业项目经验丰富'],
    cons: ['4 年 3 跳，稳定性风险高', '项目深度不足'],
    interview: [],
    skills: ['React', 'Vue', 'Node.js'],
  },
  {
    id: 'R-9829',
    name: '杨梓童',
    gender: '女',
    age: 33,
    edu: '本科 · 北京理工大学',
    yoe: 8,
    current: '某创业公司 · 前端负责人',
    expected: '35-45K',
    location: '北京',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '3 天前',
    score: 58,
    breakdown: { skill: 50, experience: 88, education: 70, project: 62, stability: 30 },
    summary: '8 年经验主要分布在创业公司，技能栈偏 jQuery / Vue2 时代，与现代前端栈匹配较弱。',
    pros: ['管理经验'],
    cons: ['6 段经历，平均每段 1.3 年', '技能栈滞后于岗位要求'],
    interview: [],
    skills: ['Vue', 'jQuery', 'Node.js', '团队管理'],
  },
  {
    id: 'R-9830',
    name: '赵雨桐',
    gender: '女',
    age: 25,
    edu: '本科 · 普通本科',
    yoe: 2,
    current: '携程 · 前端工程师',
    expected: '20-30K',
    location: '上海',
    status: 'AI 已评分',
    appliedFor: 'JD-2024-0118',
    appliedAt: '4 天前',
    score: 51,
    breakdown: { skill: 60, experience: 35, education: 50, project: 55, stability: 80 },
    summary: '2 年前端经验，主要承担页面开发，年限和深度都不满足。',
    pros: ['年轻有上升空间'],
    cons: ['年限严重不足', '项目复杂度低'],
    interview: [],
    skills: ['React', 'HTML/CSS'],
  },
];

export function findJob(id: string): Job | undefined {
  return SEED_JOBS.find((j) => j.id === id);
}

export function findResume(id: string): Resume | undefined {
  return SEED_RESUMES.find((r) => r.id === id);
}

export function resumesForJob(jobId: string): Resume[] {
  return SEED_RESUMES.filter((r) => r.appliedFor === jobId);
}
